//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_products
    {
        public int id_inv_prod { get; set; }
        public int fk_product { get; set; }
        public int fact_amount { get; set; }
        public int residue { get; set; }
        public int shortage { get; set; }
        public int surplus { get; set; }
        public int fk_user { get; set; }
        public int fk_shop { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Shops Shops { get; set; }
        public virtual Users Users { get; set; }
    }
}
