//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts_employees
    {
        public int id_post_employee { get; set; }
        public int fk_emp { get; set; }
        public int fk_post { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Posts Posts { get; set; }
    }
}
